/**
 * SquirrelDB C Client SDK - Cache (Redis-compatible)
 * Generated by sdk-generator v0.1.0
 * DO NOT EDIT MANUALLY
 */

#ifndef SQUIRRELDB_CACHE_H
#define SQUIRRELDB_CACHE_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Cache error codes */
typedef enum {
  SQRL_CACHE_OK = 0,
  SQRL_CACHE_ERR_CONNECT = 1,
  SQRL_CACHE_ERR_SEND = 2,
  SQRL_CACHE_ERR_RECV = 3,
  SQRL_CACHE_ERR_PROTOCOL = 4,
  SQRL_CACHE_ERR_SERVER = 5,
  SQRL_CACHE_ERR_MEMORY = 6,
  SQRL_CACHE_ERR_CLOSED = 7,
} sqrl_cache_error_t;

/* Forward declaration */
typedef struct sqrl_cache sqrl_cache_t;

/* Cache options */
typedef struct {
  const char *host;
  uint16_t port;
  int timeout_ms;
} sqrl_cache_options_t;

/* Initialization */
sqrl_cache_options_t sqrl_cache_options_default(void);
const char *sqrl_cache_error_string(sqrl_cache_error_t err);

/* Connection */
sqrl_cache_error_t sqrl_cache_connect(sqrl_cache_t **cache_out, const sqrl_cache_options_t *options);
void sqrl_cache_disconnect(sqrl_cache_t *cache);

/* String operations */
sqrl_cache_error_t sqrl_cache_get(sqrl_cache_t *cache, const char *key, char **value_out);
sqrl_cache_error_t sqrl_cache_set(sqrl_cache_t *cache, const char *key, const char *value, int64_t ttl_seconds);
sqrl_cache_error_t sqrl_cache_del(sqrl_cache_t *cache, const char *key, bool *deleted);
sqrl_cache_error_t sqrl_cache_exists(sqrl_cache_t *cache, const char *key, bool *exists);

/* TTL operations */
sqrl_cache_error_t sqrl_cache_expire(sqrl_cache_t *cache, const char *key, int64_t seconds, bool *success);
sqrl_cache_error_t sqrl_cache_ttl(sqrl_cache_t *cache, const char *key, int64_t *ttl_out);
sqrl_cache_error_t sqrl_cache_persist(sqrl_cache_t *cache, const char *key, bool *success);

/* Numeric operations */
sqrl_cache_error_t sqrl_cache_incr(sqrl_cache_t *cache, const char *key, int64_t *result);
sqrl_cache_error_t sqrl_cache_decr(sqrl_cache_t *cache, const char *key, int64_t *result);
sqrl_cache_error_t sqrl_cache_incrby(sqrl_cache_t *cache, const char *key, int64_t amount, int64_t *result);
sqrl_cache_error_t sqrl_cache_decrby(sqrl_cache_t *cache, const char *key, int64_t amount, int64_t *result);

/* Bulk operations */
sqrl_cache_error_t sqrl_cache_mget(sqrl_cache_t *cache, const char **keys, size_t count, char ***values_out);
sqrl_cache_error_t sqrl_cache_mset(sqrl_cache_t *cache, const char **keys, const char **values, size_t count);

/* Key operations */
sqrl_cache_error_t sqrl_cache_keys(sqrl_cache_t *cache, const char *pattern, char ***keys_out, size_t *count_out);
sqrl_cache_error_t sqrl_cache_dbsize(sqrl_cache_t *cache, int64_t *size_out);
sqrl_cache_error_t sqrl_cache_flushdb(sqrl_cache_t *cache);

/* Server operations */
sqrl_cache_error_t sqrl_cache_ping(sqrl_cache_t *cache);
sqrl_cache_error_t sqrl_cache_info(sqrl_cache_t *cache, char **info_out);

#ifdef __cplusplus
}
#endif

#endif /* SQUIRRELDB_CACHE_H */
