/**
 * SquirrelDB C Client SDK
 * Generated by sdk-generator v0.1.0
 * DO NOT EDIT MANUALLY
 */

#ifndef SQUIRRELDB_H
#define SQUIRRELDB_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Version */
#define SQRL_VERSION_MAJOR 
#define SQRL_VERSION_MINOR 
#define SQRL_VERSION_PATCH 
#define SQRL_VERSION_STRING "0.1.0"

/* Protocol constants */
#define SQRL_PROTOCOL_VERSION 0x01
#define SQRL_MAX_MESSAGE_SIZE (16 * 1024 * 1024)
#define SQRL_DEFAULT_PORT 8082

/* Error codes */
typedef enum {
  SQRL_OK = 0,
  SQRL_ERR_CONNECT = 1,
  SQRL_ERR_HANDSHAKE = 2,
  SQRL_ERR_VERSION_MISMATCH = 3,
  SQRL_ERR_AUTH_FAILED = 4,
  SQRL_ERR_SEND = 5,
  SQRL_ERR_RECV = 6,
  SQRL_ERR_TIMEOUT = 7,
  SQRL_ERR_CLOSED = 8,
  SQRL_ERR_INVALID_ARG = 9,
  SQRL_ERR_MEMORY = 10,
  SQRL_ERR_ENCODE = 11,
  SQRL_ERR_DECODE = 12,
  SQRL_ERR_SERVER = 13,
  SQRL_ERR_NOT_FOUND = 14,
} sqrl_error_t;

/* Encoding formats */
typedef enum {
  SQRL_ENCODING_MSGPACK = 0x01,
  SQRL_ENCODING_JSON = 0x02,
} sqrl_encoding_t;

/* Change event types */
typedef enum {
  SQRL_CHANGE_INITIAL = 0,
  SQRL_CHANGE_INSERT = 1,
  SQRL_CHANGE_UPDATE = 2,
  SQRL_CHANGE_DELETE = 3,
} sqrl_change_type_t;

/* Forward declarations */
typedef struct sqrl_client sqrl_client_t;
typedef struct sqrl_subscription sqrl_subscription_t;

/* Document structure */
typedef struct {
  char *id;
  char *collection;
  char *data;
  char *created_at;
  char *updated_at;
} sqrl_document_t;

/* Change event structure */
typedef struct {
  sqrl_change_type_t type;
  sqrl_document_t *document;
  sqrl_document_t *new_doc;
  char *old_data;
} sqrl_change_event_t;

/* Connection options */
typedef struct {
  const char *auth_token;
  bool use_msgpack;
  int connect_timeout_ms;
  int request_timeout_ms;
} sqrl_options_t;

/* Subscription callback */
typedef void (*sqrl_change_callback_t)(
  const sqrl_change_event_t *event,
  void *user_data
);

/* Initialization */
sqrl_error_t sqrl_init(void);
void sqrl_cleanup(void);
const char *sqrl_error_string(sqrl_error_t err);

/* Connection */
sqrl_options_t sqrl_options_default(void);
sqrl_error_t sqrl_connect(sqrl_client_t **client_out, const char *host, uint16_t port, const sqrl_options_t *options);
void sqrl_disconnect(sqrl_client_t *client);
const char *sqrl_session_id(const sqrl_client_t *client);
bool sqrl_is_connected(const sqrl_client_t *client);
sqrl_error_t sqrl_ping(sqrl_client_t *client);

/* Document operations */
sqrl_error_t sqrl_query(sqrl_client_t *client, const char *query, char **result_out);
sqrl_error_t sqrl_insert(sqrl_client_t *client, const char *collection, const char *data, sqrl_document_t **doc_out);
sqrl_error_t sqrl_update(sqrl_client_t *client, const char *collection, const char *document_id, const char *data, sqrl_document_t **doc_out);
sqrl_error_t sqrl_delete(sqrl_client_t *client, const char *collection, const char *document_id, sqrl_document_t **doc_out);
sqrl_error_t sqrl_list_collections(sqrl_client_t *client, char ***names_out, size_t *count_out);

/* Subscriptions */
sqrl_error_t sqrl_subscribe(sqrl_client_t *client, const char *query, sqrl_change_callback_t callback, void *user_data, sqrl_subscription_t **sub_out);
sqrl_error_t sqrl_unsubscribe(sqrl_subscription_t *sub);
const char *sqrl_subscription_id(const sqrl_subscription_t *sub);

/* Memory management */
void sqrl_document_free(sqrl_document_t *doc);
void sqrl_change_event_free(sqrl_change_event_t *event);
void sqrl_string_free(char *str);
void sqrl_string_array_free(char **arr, size_t count);

#ifdef __cplusplus
}
#endif

#endif /* SQUIRRELDB_H */
